server:
  servlet:
    context-path: /dxp
  port: 8080
logging:
  pattern:
    console: "%clr([%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}]){faint} %clr([${LOG_LEVEL_PATTERN:%5p}]) %clr([${PID:- }]){magenta} %clr([%15.15t]){faint} %clr([%-80.80logger{79}]){cyan} %clr([%4.4L]) %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"